### PR TITLE
Forcibly remove existing manifest before creating a new one

### LINKED ISSUE #102: [BUG] Check if multiarch manifest already exists, overwrite if so
### Version

redhat-actions/buildah-build@v2

### Describe the bug

We are using this action to build multiarch images on our own runners. However when a build is running on the same runner multiple times we get the following error:
```
/bin/buildah manifest create 12345678901.dkr.ecr.eu-west-1.amazonaws.com/base-image-java:9-move-to-gha
error creating image to hold manifest list: 
  image name "12345678901.dkr.ecr.eu-west-1.amazonaws.com/base-image-java:9-move-to-gha" is already associated
  with image "b13b58c4add1afbad60f0062ad3beb2d5fc5c5b11d6f0881213214dd4d6e10de": that name is already in use
```

It would be great if the action would check if the manifest already exists and if so remove the old one first before creating a new one.

### Steps to reproduce, workflow links, screenshots

1. Run a multiarch build with the same tag on the same runner twice

### PR DESCRIPTION
**Pull request by der-eismann**
### Description

We are using this action to build multiarch images on our own runners. However when a build is running on the same runner multiple times we get the following error:
```
/bin/buildah manifest create 12345678901.dkr.ecr.eu-west-1.amazonaws.com/base-image-java:9-move-to-gha
error creating image to hold manifest list: 
  image name "12345678901.dkr.ecr.eu-west-1.amazonaws.com/base-image-java:9-move-to-gha" is already associated
  with image "b13b58c4add1afbad60f0062ad3beb2d5fc5c5b11d6f0881213214dd4d6e10de": that name is already in use
```

This change executes a `manifest rm` and ignores the return code. Originally I was planning to do `manifest exists` and then conditionally remove, but unfortunately this feature exists only in podman and not in buildah ([yet](https://github.com/containers/buildah/pull/4220)). 

### Related Issue(s)

Fixes #102

### Checklist

- [ ] This PR includes a documentation change
- [x] This PR does not need a documentation change
---
- [ ] This PR includes test changes
- [ ] This PR's changes are already tested
---
- [x] This change is not user-facing
- [ ] This change is a patch change
- [ ] This change is a minor change
- [ ] This change is a major (breaking) change

### Changes made

- Force-remove existing manifest before creating a new one

### CODE REVIEW

**Comment by divyansh42** [comment]
@der-eismann Thanks for the PR!
Could you please rebase your PR.

**Comment by der-eismann** [comment]
> @der-eismann Thanks for the PR! Could you please rebase your PR.

Done!

**Comment by der-eismann** [comment]
@divyansh42 are you gone again?

**Review by divyansh42 — APPROVED** [review]

**Comment by divyansh42** [comment]
@der-eismann could please take a look at lint errors?

**Comment by der-eismann** [comment]
> @der-eismann could please take a look at lint errors?

Done

**Comment by der-eismann** [comment]
@divyansh42 can you please merge this?

**Review by divyansh42 — APPROVED** [review]

**Comment by divyansh42** [comment]
@der-eismann created a release for the same.
You can use this in `v2` or `v2.12`
Thanks!

**Pull request merged**
