### PR TITLE
Update Action to Node 20

### PR DESCRIPTION
**Pull request by der-eismann**
### Description

Same procedure as ~every year~ in #109. 
https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/

### Checklist

- [ ] This PR includes a documentation change
- [x] This PR does not need a documentation change
---
- [ ] This PR includes test changes
- [x] This PR's changes are already tested
---
- [ ] This change is not user-facing
- [ ] This change is a patch change
- [ ] This change is a minor change
- [x] This change is a major (breaking) change

### Changes made

- Update GitHub Actions workflows to latest versions
- Update dependencies & run on Node 20

### CODE REVIEW

**Comment by rgolangh** [comment]
Can this be approved? - github is deprecating node 16 and this action may not be usable at some stage.

**Review by divyansh42 — APPROVED** [review]

**Comment by ctron** [comment]
@divyansh42 can this be merged?

**Comment by divyansh42** [comment]
Thanks for your PR @der-eismann 🎉 
I will be creating a release for this update soon.

**Comment by ctron** [comment]
Is there a chance to get this released?

**Comment by strangiato** [comment]
Seconded on getting a release out with this.  Any update on when that might happen?

**Comment by SimonDMurray** [comment]
Also would like a release!!!

**Comment by dylanmtaylor** [comment]
Please provide a tagged release with this.

**Comment by divyansh42** [comment]
Fix has been released with the version `v2.13` and `v2`
Apologies for the delay as we were not able to look at it due to the multiple priorities.

**Pull request merged**
